version: '2'

services:
  site:
    build:
      context: .
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
#    network_mode: "host"
    ports:
      - "8000:8000"
    command: ["flask", "run", "--host=0.0.0.0"]
